AppBundle\Entity\Comment:
    type: entity

    manyToOne:
        news:
            targetEntity: Uppler\NewsBundle\Model\NewsInterface
            inversedBy: comments
            joinColumn:
                name: news_id
                referencedColumnName: id
