Uppler\CommentBundle\Model\Comment:
    type: mappedSuperclass
    id:
        id:
            type: integer
            generator:
                strategy: AUTO

    fields:
        content:
            type: text
        author:
            type: string
            length: 120
        publicationDate:
            type: datetime
