Uppler\NewsBundle\Model\News:
    type: mappedSuperclass
    id:
        id:
            type: integer
            generator:
                strategy: AUTO

    fields:
        title:
            type: string
            length: 50
            unique: true
        content:
            type: text
        author:
            type: string
            length: 120
        publicationDate:
            type: datetime
