# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        entity_managers:
            app:
                mappings:
                    AppBundle:
                        mapping:              true
                        type:                 yml
                        dir:                  "Resources/config/doctrine/mapping"

        # Matches interfaces with implementing entities
        resolve_target_entities:
            Uppler\NewsBundle\Model\NewsInterface: AppBundle\Entity\News
            Uppler\CommentBundle\Model\CommentInterface: AppBundle\Entity\Comment