security:
    providers:
        in_memory:
            memory:
                users:
                    Mathieu:
                        password: passMathieu
                        roles: 'ROLE_USER'
                    Emilien:
                        password: passEmilien
                        roles: 'ROLE_ADMIN'

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            #http_basic: ~
            form_login:
                login_path: login
                check_path: login
                #csrf_token_generator: security.csrf.token_manager
                csrf_parameter: _token
            logout:
                path:   /logout
                target: /

    access_control:
        - { path: ^/news, roles: [IS_AUTHENTICATED_FULLY] }
        - { path: ^/, roles: [IS_AUTHENTICATED_ANONYMOUSLY] }
